### GLOBAL SETTINGS
### DISCOVERY STRATEGIES: FOR EXAMPLE: MAIL, NETWORK, COMPANY
strategy: "MAIL"
indexlogo: "ice.png"
### LIST OF IDPs WITH SETTINGS
### FOR CIDR, use http://phpfunk.com/uncategorized/cidr-notation-explained-simply/
###           or http://www.subnet-calculator.com/cidr.php
idps:
  -
    name: "Okta Central"
    type: "okta"
    logo: "central.png"
    url: "https://oktacentral.oktapreview.com"
    acs:
    mailDomain:
      - oktacentral.com
      - otkacentral.org
    cidr: "192.168.0.0/24"
  -
    name: "Okta Ice"
    type: "okta"
    logo: "ice.png"
    url: "https://oktaice.oktapreview.com"
    acs: "https://oktacentral.oktapreview.com/sso/saml2/xpto"
    mailDomain:
      - oktaice.com
    cidr: "192.168.2.0/24"
  -
    name: "Milk Producer Inc"
    type: "adfs"
    logo: "milk.png"
    url: "https://adfs.milkproducer.com/adfs/ls/idpinitiatedsignon"
    acs: "OktaIce"
    mailDomain:
      - oktaice.local
    cidr: "10.0.0.0/24"
  -
    name: "Vanilla Rocks"
    type: "saml"
    logo: "vanilla.png"
    url: "https://oracleoam.vanillarocks.com/oamfed/idp/initiatesso"
    acs: "https://oktacentral.oktapreview.com/sso/saml2/xpto"
    mailDomain:
      - vanilla.com
    cidr: "10.1.0.0/24"